### ISSUE TITLE
result empty althought dependencies exists

### ISSUE THREAD

**Issue by stchevalier** [techpavan/mvn-repo-cleaner#4]
[jenkins@altair31jenkinsintboappli1 mvn-repo_cleaner]$ java -jar mvn-repo-cleaner.jar
*********** Files to be deleted ***********

FORCED_SNAPSHOT :

FORCED_SOURCE :

FORCED_JAVADOC :

ACCESS_DATE :

DOWNLOAD_DATE :

NON_LATEST :

FORCED_ARTIFACT :

FORCED_GROUP :

*********** Files skipped ***********

RESERVED :

LATEST :

IGNORED_GROUP :

IGNORED_ARTIFACT :

RETAIN_OLD :

*********** Beginning to Delete Files ***********

*********** Deletion Completed ***********

*********** Files having error in deletion ***********

**Comment by techpavan** [comment]
It might be possible that `.m2` path is not `${USER_HOME}/.m2`, but a custom one in your environment. This can be handled using the switch `--path` or `-p`. 

If `${USER_HOME}/.m2` does not exist, then it would throw an error, but as there is no such error in your case, this location might exist, but not being configured as a repository to persist the artifacts.

**Comment by stchevalier** [comment]
Hi,

with -p it's the same result

[jenkins@altair31jenkinsintboappli1 ISU_COMMON]$ ls
3.10.10-SNAPSHOT  3.10.6-SNAPSHOT  3.11.2-SNAPSHOT  3.11.9-SNAPSHOT   3.12.4-SNAPSHOT  3.12.9-SNAPSHOT  3.13.4-SNAPSHOT  3.14.2-SNAPSHOT  3.7.3-SNAPSHOT  3.9.11           3.9.1-SNAPSHOT  3.9.6-SNAPSHOT
3.10.2-SNAPSHOT   3.10.7-SNAPSHOT  3.11.3-SNAPSHOT  3.12.0-SNAPSHOT   3.12.5           3.13.1-SNAPSHOT  3.13.5-SNAPSHOT  3.15.0           3.8.0           3.9.11-SNAPSHOT  3.9.2-SNAPSHOT  3.9.7-SNAPSHOT
3.10.3-SNAPSHOT   3.10.8-SNAPSHOT  3.11.5-SNAPSHOT  3.12.11-SNAPSHOT  3.12.5-SNAPSHOT  3.13.2-SNAPSHOT  3.14.0           3.15.1-SNAPSHOT  3.8.0-SNAPSHOT  3.9.12           3.9.3-SNAPSHOT  3.9.8-SNAPSHOT
3.10.4-SNAPSHOT   3.10.9-SNAPSHOT  3.11.6-SNAPSHOT  3.12.1-SNAPSHOT   3.12.6-SNAPSHOT  3.13.3-SNAPSHOT  3.14.1           3.7.2            3.8.1-SNAPSHOT  3.9.12-SNAPSHOT  3.9.4-SNAPSHOT  3.9.9-SNAPSHOT
3.10.5-SNAPSHOT   3.11.1-SNAPSHOT  3.11.7-SNAPSHOT  3.12.2-SNAPSHOT   3.12.7-SNAPSHOT  3.13.4           3.14.1-SNAPSHOT  3.7.2-SNAPSHOT   3.9.0-SNAPSHOT  3.9.13-SNAPSHOT  3.9.5-SNAPSHOT
[jenkins@altair31jenkinsintboappli1 ISU_COMMON]$ pwd
/home/jenkins/.m2/repository/fr/acoss/isu/ISU_COMMON



[jenkins@altair31jenkinsintboappli1 mvn-repo_cleaner]$ java -jar mvn-repo-cleaner.jar -p /home/jenkins/.m2
*********** Files to be deleted ***********


FORCED_SNAPSHOT :



FORCED_SOURCE :



FORCED_JAVADOC :



ACCESS_DATE :



DOWNLOAD_DATE :



NON_LATEST :



FORCED_ARTIFACT :



FORCED_GROUP :



*********** Files skipped ***********


RESERVED :



LATEST :



IGNORED_GROUP :



IGNORED_ARTIFACT :



RETAIN_OLD :



*********** Beginning to Delete Files ***********


*********** Deletion Completed ***********


*********** Files having error in deletion ***********

[jenkins@altair31jenkinsintboappli1 mvn-repo_cleaner]$

**Comment by techpavan** [comment]
The way this application starts its processing is by listing the pom files first. Can you check for the permissions of the directories that are listed and the contents within?

**Comment by techpavan** [comment]
@stchevalier Did you check with the permissions? Was that the issue?
