### ISSUE TITLE
Will not compile with Java 11+

### ISSUE THREAD

**Issue by TIBCOeddie** [techpavan/mvn-repo-cleaner#6]
Java 8 - mvn package succeeds
Java 11+ will fail with:

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project mvn-repo-cleaner: Fatal error compiling: java.lang.ExceptionInInitializerError: com.sun.tools.javac.code.TypeTags -> [Help 1]`

**Comment by tinynet** [comment]
I managed to compile it with Java 11 and lombok version 1.18.2

**Comment by techpavan** [comment]
This is fixed in https://github.com/techpavan/mvn-repo-cleaner/releases/tag/release_v1.0.2_07112022
