### ISSUE TITLE
Add option '--downloadedAfter, -da'

### ISSUE THREAD

**Issue by packpaul** [techpavan/mvn-repo-cleaner#8]
I was using a separate `<project1>/_m2/repository` and by mistake started a build for an other project by
```
$ mvn -s <project1>/_m2/settings.xml
```
instead of
```
$ mvn -s <project2>/_m2/settings.xml
```
And after this m2-repository of the first project got littered. Now I would like to clean artifacts that were downloaded today.

**Comment by techpavan** [comment]
Thanks for the PR. Its now released - https://github.com/techpavan/mvn-repo-cleaner/releases/tag/release_v1.0.2_07112022
